version: "3.8"
services:
  db:
    image: postgres
    container_name: fhir-bridge-postgres
    ports:
      - 9999:5432
    environment:
      POSTGRES_USER: fhir_bridge
      POSTGRES_PASSWORD: fhir_bridge