version: '3'
services:
  ehrbase:
    image: ehrbase/ehrbase:0.21.1
    ports:
      - "8080:8080"
    networks:
      - ehrbase-net
    environment:
      DB_URL: jdbc:postgresql://ehrbase-database:5432/ehrbase
      DB_USER: ehrbase
      DB_PASS: ehrbase
      AUTH_TYPE: BASIC
      AUTH_USER: ehrbase-user
      AUTH_PASSWORD: SuperSecretPassword
      SYSTEM_NAME: local.ehrbase.org
    depends_on:
      - ehrbase-database

  ehrbase-database:
    image: ehrbase/ehrbase-postgres:13.4
    networks:
      - ehrbase-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      EHRBASE_USER: ehrbase
      EHRBASE_PASSWORD: ehrbase

  fhir-bridge-database:
    image: postgres:13.4
    ports:
      - "9999:5432"
    environment:
      POSTGRES_USER: fhir_bridge
      POSTGRES_PASSWORD: fhir_bridge

networks:
  ehrbase-net: { }
