ehrbase:
  address: localhost
  port: 8080
  path: /ehrbase/rest/openehr/v1/
fhir-bridge:
  fhir:
    narrative-generation: false
    url-mapping: /fhir/*
    validation:
      terminology:
        mode: off
        #remote:
        #server-url: https://r4.ontoserver.csiro.au/fhir/
logging:
  level:
    ca.uhn.fhir: info
    org.ehrbase.fhirbridge: info
    org.hl7.fhir: info
server:
  servlet:
    context-path: /fhir-bridge
  port: 8888
spring:
  jpa:
    properties:
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory