fhir-bridge:
  fhir:
    narrative-generation: false
    url-mapping: /fhir/*
    validation:
      terminology:
        server-url: https://r4.ontoserver.csiro.au/fhir/
logging:
  level:
    ca.uhn.fhir: info
    org.hl7.fhir: warn
    org.ehrbase.fhirbridge: info
server:
  servlet:
    context-path: /fhir-bridge
  port: 8080