fhir-bridge:
  fhir:
    narrative-generation: true
    url-mapping: /fhir/*
logging:
  level:
    ca.uhn.fhir: info
    org.hl7.fhir: warn
    org.ehrbase.fhirbridge: info
server:
  servlet:
    context-path: /fhir-bridge
  port: 8080