fhir-bridge:
  fhir:
    narrative-generation: false
    url-mapping: /fhir/*
logging:
  level:
    ca.uhn.fhir: info
    org.hl7.fhir: warn
    org.ehrbase.fhirbridge: info
server:
  servlet:
    context-path: /fhir-bridge
  port: 8888

ehrbase:
  address: localhost
  port: 8080
  path: /ehrbase/rest/openehr/v1/